suppressMessages(library(dplyr))
prj <- rgcam::loadProject("debug/case1_chemical_feedback_Sector/Input/u0909r_Ref_u0909.dat")
q <- rgcam::getQuery(prj, "primary energy consumption with CCS by region (direct equivalent)")
print(names(q))
cat("--- Units by fuel ---\n"); print(q %>% distinct(fuel, Units) %>% as.data.frame())
cat("--- uranium vs e nuclear, selected regions/years ---\n")
print(q %>% filter(fuel %in% c("e nuclear","uranium"), region %in% c("South Korea","USA","China","Japan"), year %in% c(2015,2020,2030,2050)) %>% select(region, fuel, year, value) %>% tidyr::pivot_wider(names_from=fuel, values_from=value) %>% as.data.frame())
cat("--- regions with nonzero uranium ---\n"); print(q %>% filter(fuel=="uranium", value!=0) %>% distinct(region) %>% pull(region))
cat("--- ceilings sample ---\n"); print(q %>% filter(grepl("ceiling", fuel)) %>% group_by(fuel, Units) %>% summarise(n=n(), regions=n_distinct(region), maxv=max(value), .groups="drop") %>% as.data.frame())
